Feature: Make currency denominations configurable.
AcroMedia/commerce_pos pull request #42
Opened 2017-05-01 04:45 UTC by shabananavas

Issue: https://www.drupal.org/node/2862645

2017-05-01 15:54 UTC, wildkatana commented on modules/currency_denomination/includes/commerce_pos_currency_denomination.admin.inc
> +        'exists' => 'commerce_pos_currency_denomination_name_exists',
Nice 👍

2017-05-01 15:57 UTC, wildkatana commented on modules/currency_denomination/includes/commerce_pos_currency_denomination.admin.inc
> +      t('Cancel')
Really minor but I've noticed this a few places, there should be a trailing comma for multi-line arrays.

2017-05-01 15:59 UTC, wildkatana commented on modules/currency_denomination/includes/commerce_pos_currency_denomination.admin.inc
> +      $output .= t('<p>Currently, no denominations have been added for this denomination type.</p>');
You could use the 'empty' parameter for theme_table for this if you want to simplify some of the logic here: https://api.drupal.org/api/drupal/includes%21theme.inc/function/theme_table/7.x

2017-05-01 16:08 UTC, wilderuncat requested changes
Looks great overall. Nice and clean. Just one minor thing that I think blocks it.

2017-05-01 16:08 UTC, wildkatana commented on modules/keypad/commerce_pos_keypad.info
> +dependencies[] = commerce_pos:commerce_pos_currency_denomination
This is really cool. But according to Drupal.org, we need to also require Drupal 7.40 when we use this new format: https://www.drupal.org/docs/7/creating-custom-modules/writing-module-info-files-drupal-7x#dependencies

dependencies[] = drupal:system (>= 7.40)

2017-05-02 15:05 UTC, shabananavas commented on modules/currency_denomination/includes/commerce_pos_currency_denomination.admin.inc
> +      t('Cancel')
These are arguments for the confirm_form() function, so no comma needed here.

2017-05-02 16:04 UTC, shabananavas commented on modules/currency_denomination/includes/commerce_pos_currency_denomination.admin.inc
> +      $output .= t('<p>Currently, no denominations have been added for this denomination type.</p>');
Yeah, I missed that one. Thanks!

2017-05-02 16:05 UTC, shabananavas commented on modules/keypad/commerce_pos_keypad.info
> +dependencies[] = commerce_pos:commerce_pos_currency_denomination
Thanks, will add that.

2017-05-05 04:38 UTC, wilderuncat approved these changes

2017-05-05 22:46 UTC, smmccabe commented
Committed via d.o patch, thnx!

2017-05-05 22:46 UTC, closed without merging